In [7]:
import sys
import numpy as np
import pandas as pd
from sklearn import model_selection

In [17]:
test_values=np.loadtxt("test_ccpp_x_test.csv",delimiter=',')
#convert dictionery into dataframe

df=pd.DataFrame(test_values)
df[4]=1
finaltest=df.values
finaltest.shape
df

0      1        2      3  4
0     11.95  42.03  1017.58  90.89  1
1     12.07  38.25  1012.67  81.66  1
2     26.91  74.99  1005.64  78.98  1
3     20.58  39.53  1005.68  62.09  1
4     16.78  37.20  1011.97  68.94  1
5     22.46  58.49  1011.50  70.54  1
6      8.26  40.96  1025.23  89.22  1
7     20.96  69.48  1011.04  82.63  1
8      4.97  40.64  1020.91  94.28  1
9     25.61  67.69  1009.22  68.76  1
10    28.69  67.79  1011.01  66.40  1
11    27.58  73.06  1009.63  88.31  1
12    12.57  39.30  1019.57  72.44  1
13    16.15  41.85  1016.54  81.58  1
14    25.18  62.96  1020.04  59.08  1
15    18.68  53.29  1018.16  75.01  1
16     4.62  38.44  1016.09  73.14  1
17    22.51  66.49  1014.59  63.03  1
18    30.66  73.77  1003.13  78.09  1
19    29.01  64.79  1017.62  44.31  1
20    24.75  69.89  1015.29  82.01  1
21     5.25  42.85  1013.75  89.67  1
22    15.72  56.89  1013.35  85.06  1
23     9.27  40.22  1008.10  89.24  1
24    28.83  71.32  1006.28  75.65  1
25    29.57  67.83  1009.19  55.74  1
26    12.65  44.34  1014.74  92.81  1
27    12.23  41.58  1018.76  87.66  1
28    31.05  62.70  1009.35  55.27  1
29     9.24  41.40  1018.34  84.91  1
...     ...    ...      ...    ... ..
2362  29.51  75.60  1017.92  50.61  1
2363  24.27  63.90  1013.50  61.09  1
2364  29.87  69.13  1001.08  72.75  1
2365  23.62  49.21  1014.10  49.54  1
2366  11.69  35.76  1019.02  55.60  1
2367  15.28  43.71  1024.32  81.24  1
2368  14.81  40.71  1018.54  73.00  1
2369  11.97  45.51  1016.84  81.47  1
2370  17.29  42.86  1014.38  72.30  1
2371  32.96  73.03  1013.56  54.03  1
2372  26.45  64.27  1013.23  60.92  1
2373  22.95  45.61  1013.65  73.92  1
2374  30.70  71.58  1010.00  48.96  1
2375  18.32  66.86  1012.02  70.00  1
2376  26.85  66.86  1006.78  69.40  1
2377  13.46  44.71  1014.51  50.00  1
2378  30.19  68.08  1010.95  50.34  1
2379  15.11  40.71  1017.96  69.31  1
2380  14.60  44.47  1028.46  69.96  1
2381  18.40  43.69  1016.59  52.44  1
2382  20.28  62.52  1017.89  75.67  1
2383  13.01  41.58  1020.82  78.41  1
2384  15.68  43.70  1015.09  58.96  1
2385  23.55  61.87  1009.65  54.83  1
2386  30.99  69.82  1009.41  50.84  1
2387  29.49  69.71  1009.34  56.35  1
2388  27.69  65.34  1014.31  46.59  1
2389  24.32  66.25  1009.09  91.89  1
2390  23.49  42.80  1013.96  65.31  1
2391  21.76  60.27  1018.96  85.06  1

[2392 rows x 5 columns]

In [30]:
train_inputs=np.loadtxt("training_ccpp_x_y_train.csv",delimiter=',')
print (train_inputs)
y=train_inputs[:,train_inputs.shape[1]-1]
x=train_inputs[:,0:train_inputs.shape[1]-1]

print(x)
print(y)


[[   8.58   38.38 1021.03   84.37  482.26]
 [  21.79   58.2  1017.21   66.74  446.94]
 [  16.64   48.92 1011.55   78.76  452.56]
 ...
 [  29.8    69.34 1009.36   64.74  437.65]
 [  16.37   54.3  1017.94   63.63  459.97]
 [  30.11   62.04 1010.69   47.96  444.42]]
[[   8.58   38.38 1021.03   84.37]
 [  21.79   58.2  1017.21   66.74]
 [  16.64   48.92 1011.55   78.76]
 ...
 [  29.8    69.34 1009.36   64.74]
 [  16.37   54.3  1017.94   63.63]
 [  30.11   62.04 1010.69   47.96]]
[482.26 446.94 452.56 ... 437.65 459.97 444.42]


In [33]:
#printiing the values of x and y as a trained data
#print(x,"\n",y)
#print('\n',x.shape," ",y.shape)
df=pd.DataFrame(x)
df[4]=1
x=df.values
x.shape

(7176, 5)

In [37]:
m_values=(np.zeros(x.shape[1])).reshape(-1,1)
print(m_values)
print(df.head())
print(np.dot(x,m_values))



[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
       0      1        2      3  4
0   8.58  38.38  1021.03  84.37  1
1  21.79  58.20  1017.21  66.74  1
2  16.64  48.92  1011.55  78.76  1
3  31.38  71.32  1009.17  60.42  1
4   9.20  40.03  1017.05  92.46  1
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [38]:
def cost(x,y,m_values):
    total=0
    for i in range(len(x)):
        total=total+(1/len(x))*( ( y[i] - ( np.dot( x[i,:],m_values ) ).sum() )**2 )
        
    return total

In [39]:
def single_gradient(rate,m_values,x,y):
    m_slope=(np.zeros(x.shape[1]).reshape(-1,1))
    m=len(x)
    for i in range(len(x)):
        row=x[i,:]
        for j in range(len(m_values)):
            m_slope[j]+=(-2/m)*(y[i]-np.dot(row,m_values).sum())*row[j]
    
    return m_values-rate*m_slope


In [41]:

def gd(rate,iteration,x,y):
    m_values=(np.zeros(x.shape[1])).reshape(-1,1)
    
    for i in range(iteration):
        m_values=single_gradient(rate,m_values,x,y)
        print(i," cost is ",cost(x,y,m_values))
        
    return m_values

In [46]:
def run():
    rate=.000001
    iteration=100
    final_m=gd(rate,iteration,x,y)
    
    yfinal=np.zeros(len(finaltest))
    yfinal=yfinal.reshape(-1,1)
    print(" the value of final m is \n", final_m)
    for i in range(len(finaltest)):
        yfinal[i]=(np.dot(finaltest[i],final_m).sum()) 
        
    np.savetxt("project1ans.csv",yfinal,delimiter=',',fmt='%1.5f')




In [47]:
run()

0  cost is  237116.9153476344
1  cost is  271882.1255768481
2  cost is  311750.0878720959
3  cost is  357469.76702449785
4  cost is  409900.0583638327
5  cost is  470025.9229941026
6  cost is  538976.8913048112
7  cost is  618048.2823655471
8  cost is  708725.5378320655
9  cost is  812712.1275014827
10  cost is  931961.5507511968
11  cost is  1068714.0350415877
12  cost is  1225538.6209019052
13  cost is  1405381.424008927
14  cost is  1611620.98101187
15  cost is  1848131.718831461
16  cost is  2119356.739769939
17  cost is  2430391.2897751248
18  cost is  2787078.477896192
19  cost is  3196119.045120118
20  cost is  3665197.2447092105
21  cost is  4203125.198832523
22  cost is  4820008.443378939
23  cost is  5527435.7708826605
24  cost is  6338696.937955714
25  cost is  7269032.327087479
26  cost is  8335919.252964732
27  cost is  9559400.291872669
28  cost is  10962459.802184315
29  cost is  12571455.70926189
30  cost is  14416614.666299786
31  cost is  16532599.89321231
32  cost is